package com.treloc.xtreloc.solver;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;

import edu.sc.seis.TauP.Arrival;
import edu.sc.seis.TauP.TauModel;
import edu.sc.seis.TauP.TauModelLoader;
import edu.sc.seis.TauP.TauP_Time;

/**
 * Prints a Markdown summary table of {@link Raytrace1D} vs TauP (bundled {@code prem.nd}, phase list {@code tts,S})
 * travel times and takeoff/incident angles.
 * <p>
 * Run from project root (after {@code mvn test-compile}):
 * {@code java -cp target/test-classes:target/classes:$(mvn -q dependency:build-classpath -Dmdep.outputFile=/dev/stdout -q) com.treloc.xtreloc.solver.RaytraceTauPComparisonTable}
 * <p>
 * Or write to file:
 * {@code ... RaytraceTauPComparisonTable raytrace/raytrace_vs_taup_prem_summary.md}
 */
public final class RaytraceTauPComparisonTable {

    private static final double EARTH_RADIUS_KM = 6371.0;
    private static final String BUNDLED_PREM = "velocity-models/prem.nd";

    private RaytraceTauPComparisonTable() {
    }

    public static void main(String[] args) throws Exception {
        Path out = args.length > 0 ? Path.of(args[0]) : null;
        String md = buildMarkdownReport();
        System.out.print(md);
        if (out != null) {
            Files.writeString(out, md, StandardCharsets.UTF_8);
            System.err.println("Wrote " + out.toAbsolutePath());
        }
    }

    static String buildMarkdownReport() throws Exception {
        TauModel tauModel = loadTauModelFromBundledNd(BUNDLED_PREM);
        Raytrace1D layered = Raytrace1D.load("prem.nd");

        TauP_Time taup = new TauP_Time();
        taup.setTauModel(tauModel);
        taup.clearPhaseNames();
        taup.clearArrivals();
        taup.clearPhases();
        taup.parsePhaseList("tts,S");

        double stationDepthKm = 0.1;
        StringBuilder sb = new StringBuilder(8192);
        sb.append("# Raytrace1D vs TauP (`prem.nd`, phases `tts,S`)\n\n");
        sb.append("In the layered 1D scheme, **ANG/BNG are discrete takeoff/incident angles measured from downward vertical** (radians).\n\n");
        sb.append("TauP 2.x `SeismicPhase.calcTakeoffAngle` returns **degrees**, uses a spherical model in `asin(v·p/(R−h))`, and **maps the first upgoing leg into 90°–180°** ")
            .append("via `180° − …`—so conventions differ from the flat-layer solver.\n\n");
        sb.append("Do not expect takeoff columns to line up; summary Δθ is **indicative only**. **The meaningful comparison is travel time (1D/T column).**\n\n");

        sb.append("## Regional (epicentral distance ≤ 120 km)\n\n");
        sb.append("| Δ km | z_src km | z_stn km | t_1d s | t_taup s | 1D/T | θ_takeoff 1D° | θ_takeoff T° | Δθ_take° | θ_inc 1D° | θ_inc T° |\n");
        sb.append("|-----:|---------:|---------:|-------:|---------:|-----:|--------------:|-------------:|----------:|----------:|---------:|\n");
        double[] regionalDistKm = {10, 30, 50, 100, 120};
        double regionalSrcKm = 30.0;
        for (double distKm : regionalDistKm) {
            appendRow(sb, layered, taup, distKm, regionalSrcKm, stationDepthKm);
        }

        sb.append("\n## Teleseismic\n\n");
        sb.append("| Δ km | z_src km | z_stn km | t_1d s | t_taup s | 1D/T | phase | θ_takeoff 1D° | θ_takeoff T° | Δθ_take° | θ_inc 1D° | θ_inc T° |\n");
        sb.append("|-----:|---------:|---------:|-------:|---------:|-----:|:-----:|--------------:|-------------:|----------:|----------:|---------:|\n");
        double[] teleDistKm = {500, 800, 1200, 2000, 3500, 5000};
        double[] teleSrcKm = {10, 33, 100};
        for (double distKm : teleDistKm) {
            for (double srcKm : teleSrcKm) {
                appendTeleRow(sb, layered, taup, distKm, srcKm, stationDepthKm);
            }
        }

        sb.append("\n---\n\n");
        sb.append("*Generated by `RaytraceTauPComparisonTable` (test sources).* ");
        sb.append("The application uses `Raytrace1D` only (runtime and dependency footprint); TauP is for validation tables.\n");
        return sb.toString();
    }

    private static void appendRow(
        StringBuilder sb,
        Raytrace1D layered,
        TauP_Time taup,
        double distKm,
        double srcDepthKm,
        double stationDepthKm) throws Exception {
        Raytrace1D.RaySolution sol = layered.solveFastestRay(distKm, srcDepthKm, stationDepthKm);
        taup.depthCorrect(srcDepthKm, stationDepthKm);
        taup.setSourceDepth(srcDepthKm);
        taup.calculate(Math.toDegrees(distKm / EARTH_RADIUS_KM));
        Arrival fastest = fastestArrival(taup.getArrivals());

        double tl = sol.travelTimeSeconds;
        double tt = fastest.getTime();
        double ratio = tt > 0 ? tl / tt : Double.NaN;
        double takeL = Math.toDegrees(sol.takeoffAngleRad);
        double takeT = normalizeTaupAngleDeg(fastest.getTakeoffAngle());
        double incL = Math.toDegrees(sol.incidentAngleRad);
        double incT = normalizeTaupAngleDeg(fastest.getIncidentAngle());
        double dTake = circularDiffDeg(normalizeDeg(takeL), normalizeDeg(takeT));

        sb.append(String.format(Locale.US,
            "| %.1f | %.1f | %.1f | %.4f | %.4f | %.4f | %.2f | %.2f | %.2f | %.2f | %.2f |\n",
            distKm, srcDepthKm, stationDepthKm, tl, tt, ratio, takeL, takeT, dTake, incL, incT));
    }

    private static void appendTeleRow(
        StringBuilder sb,
        Raytrace1D layered,
        TauP_Time taup,
        double distKm,
        double srcDepthKm,
        double stationDepthKm) throws Exception {
        Raytrace1D.RaySolution sol = layered.solveFastestRay(distKm, srcDepthKm, stationDepthKm);
        taup.depthCorrect(srcDepthKm, stationDepthKm);
        taup.setSourceDepth(srcDepthKm);
        taup.calculate(Math.toDegrees(distKm / EARTH_RADIUS_KM));
        Arrival fastest = fastestArrival(taup.getArrivals());

        double tl = sol.travelTimeSeconds;
        double tt = fastest.getTime();
        double ratio = tt > 0 ? tl / tt : Double.NaN;
        double takeL = Math.toDegrees(sol.takeoffAngleRad);
        double takeT = normalizeTaupAngleDeg(fastest.getTakeoffAngle());
        double incL = Math.toDegrees(sol.incidentAngleRad);
        double incT = normalizeTaupAngleDeg(fastest.getIncidentAngle());
        double dTake = circularDiffDeg(normalizeDeg(takeL), normalizeDeg(takeT));
        String ph = fastest.getName() == null ? "?" : fastest.getName();

        sb.append(String.format(Locale.US,
            "| %.0f | %.0f | %.1f | %.4f | %.4f | %.4f | %s | %.2f | %.2f | %.2f | %.2f | %.2f |\n",
            distKm, srcDepthKm, stationDepthKm, tl, tt, ratio, ph, takeL, takeT, dTake, incL, incT));
    }

    private static Arrival fastestArrival(List<Arrival> arrivals) {
        if (arrivals == null || arrivals.isEmpty()) {
            throw new IllegalStateException("TauP returned no arrivals.");
        }
        Arrival fastest = arrivals.get(0);
        for (Arrival arr : arrivals) {
            if (arr.getTime() < fastest.getTime()) {
                fastest = arr;
            }
        }
        return fastest;
    }

    private static TauModel loadTauModelFromBundledNd(String resourcePath) throws Exception {
        try (InputStream in = RaytraceTauPComparisonTable.class.getClassLoader().getResourceAsStream(resourcePath)) {
            if (in == null) {
                throw new IOException("Resource not found: " + resourcePath);
            }
            Path tmp = Files.createTempFile("xtreloc-taup-prem-", ".nd");
            tmp.toFile().deleteOnExit();
            Files.copy(in, tmp, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            return TauModelLoader.load(tmp.toAbsolutePath().toString());
        }
    }

    private static double normalizeTaupAngleDeg(double takeoffDeg) {
        if (Double.isNaN(takeoffDeg)) {
            return Double.NaN;
        }
        double d = takeoffDeg;
        if (d < 0.0) {
            d += 180.0;
        }
        return normalizeDeg(d);
    }

    private static double normalizeDeg(double d) {
        double r = d % 360.0;
        return r < 0 ? r + 360.0 : r;
    }

    private static double circularDiffDeg(double a, double b) {
        double d = Math.abs(a - b) % 360.0;
        return d > 180.0 ? 360.0 - d : d;
    }

}
